# Generated by Django 3.2.9 on 2021-12-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
